name: Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'zulu'

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Check out utils
        uses: actions/checkout@v4
        with:
          repository: tiki/core-ocean-iceberg-utils
          token: ${{ github.token }}
          path: utils
          ref: ${{ vars.UTILS_VERSION }}

      - name: Maven Install Utils
        run: cd utils && mvn clean package install

      - name: Maven Package
        run: mvn clean package

      - name: Upload Results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: target/surefire-reports/**/*.xml

      - name: Validate AWS Template
        run: |
          cd infra/function
          sam validate

      - name: Build AWS Template
        run: |
          cd infra/function
          sam build
